language: python
cache: pip

notifications:
  email:
    recipients:
      - jcline@fedoraproject.org
    on_success: never
    on_failure: always

install:
 - pip install --upgrade pip setuptools
 - pip install tox

script:
  - tox

after_success:
  - source .tox/${TOXENV}/bin/activate && pip install codecov && codecov --env TRAVIS_OS_NAME,TOXENV

env:
  global:
    - PYTHONWARNINGS=always::DeprecationWarning
matrix:
  include:
    - python: "3.6"
      env: TOXENV=lint
    - python: "3.6"
      env: TOXENV=format
    - python: "3.6"
      env: TOXENV=licenses
    - python: "3.6"
      env: TOXENV=bandit
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
      sudo: required  # Force Travis to use a Ubuntu 16.04 VM that can run 3.7
